receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp/uptrace:
    endpoint: "otlp.uptrace.dev:4317"
    headers:
      uptrace-dsn: "your-project-key@uptrace.dev/1423"
  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/uptrace]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/uptrace]
